### ISSUE TITLE
Frameworks

### ISSUE THREAD

**Issue by TimothyRLaMora734** [fattihkoca/instagram-for-macos#1]
missing frameworks to run in macOS Catalina

**Comment by fattihkoca** [comment]
> missing frameworks to run in macOS Catalina 

Thanks for information @TimothyRLaMora734. I've made it compatible with MacOS Catalina. 
**[DOWNLOAD](https://github.com/fattihkoca/instagram-for-macos/releases/download/v0.0.2/Instagram.for.MacOS.zip)**

**Comment by TimothyRLaMora734** [comment]
Thank you :)

**Comment by fattihkoca** [comment]
> missing frameworks to run in macOS Catalina
