### ISSUE TITLE
[Error] A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by AvinashDevina** [fattihkoca/instagram-for-macos#4]
Getting an Error popup while opening the app.

A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: win is not defined
    at createWindow (/Applications/Instagram.app/Contents/Resources/app/main.js:49:5)
    at App.<anonymous> (/Applications/Instagram.app/Contents/Resources/app/main.js:70:9)
    at App.emit (events.js:182:13)

Please Check

Thanks
Avinash

**Comment by fattihkoca** [comment]
> Getting an Error popup while opening the app.
> 
> A JavaScript error occurred in the main process
> Uncaught Exception:
> ReferenceError: win is not defined
> at createWindow (/Applications/Instagram.app/Contents/Resources/app/main.js:49:5)
> at App. (/Applications/Instagram.app/Contents/Resources/app/main.js:70:9)
> at App.emit (events.js:182:13)
> 
> Please Check
> 
> Thanks
> Avinash

I will detect and solve the error as soon as possible :)
