### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Steveherbert** [fattihkoca/instagram-for-macos#7]
Hey, I m new here, I have download the zip, and what should I do to use the interesting application? Would you please tell me?

**Comment by fattihkoca** [comment]
Hey, try and download the version under release section. (You can find it on the right when you open the "<> Code" tab in the UI). 
Have fun 👍

**Comment by Steveherbert** [comment]
Thanks,  I got both the zip and gz, it shows a warming when I open the application.
<img width="532" alt="截屏2020-10-22 10 42 08" src="https://user-images.githubusercontent.com/73210267/96818276-bff0c300-1453-11eb-941c-e0e0ee9ced98.png">
