### ISSUE TITLE
[Enhancement] Ability to use multiple accounts

### ISSUE THREAD

**Issue by 3raxton** [fattihkoca/instagram-for-macos#8]
Great work on this Instagram client. It's become my alternative to Flume, and I love how seamless it is on Mac! Nevertheless, I was curious if it was possible to use multiple accounts within the app. 

I realize that this is a wrapped version of the web app, which doesn't support multiple accounts, but I was curious if there is any workaround or ideas you have to add multiple accounts to the app. Is there anything that comes to mind? 

 Whether possible or not, I'm grateful for your hard work on this project! 🎉

**Comment by fattihkoca** [comment]
It's great for me to hear your beautiful thoughts! Thanks to you, I started the day happy :)

I want to give you the reward of this happiness by adding the multi-account feature you expect:
I added this feature to the `v0.0.5`: [Please try it](https://github.com/fattihkoca/instagram-for-macos/releases)

I've tested it several times. Can you examine it too? Have a nice day 🙏
